name: github pages

on:
  pull_request: 
    types: [closed]
    branches:
      - master
jobs:
  if: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        if: github.event.pull_request.merged == true

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
        if: github.event.pull_request.merged == true

      - name: Setup Hexo
        run: npm install -g hexo
        if: github.event.pull_request.merged == true

      - name: Build
        run: npx hexo --minify
        if: github.event.pull_request.merged == true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
        if: github.event.pull_request.merged == true && success()
