name: github pages

on:
  pull_request: 
    types: [closed]

jobs:
  if: github.event.pull_request.merged == 'true'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - name: Setup Hexo
      run: npm install -g hexo 

    - name: Build
      run: npx hexo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
